### ISSUE TITLE
How can I fix Ema0003?

### ISSUE THREAD

**Issue by jmsong2** [NAL-i5K/GFF3toolkit#1]
Hi,
when i run the command "python bin/gff-QC.py -g test.gff3 -f  ~/data/rice_genome/test.fasta -o test.txt",
i get the follow error information. 
INFO     Checking errors in the gff files: (test.gff3)...
Traceback (most recent call last):
  File "bin/gff-QC.py", line 90, in <module>
    if not gff3.check_parent_boundary():
  File "bin/../lib/gff3_modified/gff3_modified.py", line 243, in check_parent_boundary
    self.add_line_error(line, {'message': '{2:s}: {0:s}: {1:s}'.format(parent_feature[0]['attributes']['ID'], ','.join(['({0:s}, {1:d}, {2:d})'.format(line['seqid'], line['
start'], line['end']) for line in parent_feature]), ERROR_INFO['Ema0003']), 'error_type': 'BOUNDS', 'location': 'parent_boundary', 'eCode': 'Ema0003'})IndexError: list index out of rang

Could i know which lines in the gff have the error to fix it ?

Thanks.

**Comment by taiwaness** [comment]
Hi @jmsong2,

Thanks for the bug report. 

I've made a new commit to show which line in the input gff failing the program. Please git pull the update version, and try the program again. 

Ema0003 is to check whether a feature is properly contained within the parent feature coordinates. However, the previous version of the program would fail if the input gff present a feature alone without its parent feature. For example, a gff has exon features, but does not have the corresponding mRNA features.

Now, the new commit would show more information such as line number, instead of die directly. Hope this helps.

Please let me know if further questions. Thanks for using i5k GFF3toolkits. ^_____________^

**Comment by jmsong2** [comment]
Hi @taiwaness ,

Thanks for your kindly reply. It works well now.

Very practical it is ~
