### ISSUE TITLE
Error when running gff3_ID_generator.py

### ISSUE THREAD

**Issue by B203712-2021** [NAL-i5K/GFF3toolkit#125]
Hello, I'm currently using the gff3_ID_generator.py but it reports errors like this:
![1658964888909](https://user-images.githubusercontent.com/91726869/181390166-81ed1cf0-03ff-4299-bfc0-ffd439ecc4e4.png)

Could you please help how to fix it?

**Comment by mpoelchau** [comment]
Sorry you're having trouble with the script. Could you attach a snippet of the gff3 file to help troubleshoot (or the whole file if it's not too big/private)?

**Comment by B203712-2021** [comment]
I'm so sorry for my late response. I've tried to submitted all the two gff and gff3 files to my github becuase they're too large, and I hope you can see them. All the two files will got errors when doing gff3_ID_generator.py (the gff3 files) or gff_to_fasta. Thank you for your reponse and hope for any advice how can I fix the error.
https://github.com/B203712-2021/Project

**Comment by mpoelchau** [comment]
Hi @B203712-2021 , 

The problem is that your gff3 file has sequence-region directive lines where the end coordinate is "None", e.g.
`##sequence-region est_AJ558253.1.mrna1 1 None`

The program assumes that the end coordinate is a number (not a bad assumption but I admit the GFF3 spec doesn't explicitly state that it has to be a number, https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). Do you know why the end coordinate is 'None'?

In the meantime, you can just remove the sequence-directive lines to get the program to work.
